from typing import Any

add_body_html: Any
add_css: Any
add_head_html: Any
add_sass: Any
add_scss: Any
aggrid: Any
altair: Any
anywidget: Any
audio: Any
avatar: Any
badge: Any
button: Any
button_group: Any
card: Any
card_actions: Any
card_section: Any
carousel: Any
carousel_slide: Any
chat_message: Any
checkbox: Any
chip: Any
circular_progress: Any
clipboard: Any
code: Any
codemirror: Any
color_input: Any
color_picker: Any
colors: Any
column: Any
context: Any
context_menu: Any
dark_mode: Any
date: Any
date_input: Any
dialog: Any
download: Any
drawer: Any
dropdown_button: Any
echart: Any
editor: Any
element: Any
expansion: Any
fab: Any
fab_action: Any
footer: Any
fullscreen: Any
grid: Any
header: Any
highchart: Any
html: Any
icon: Any
image: Any
input: Any
input_chips: Any
interactive_image: Any
item: Any
item_label: Any
item_section: Any
joystick: Any
json_editor: Any
keyboard: Any
knob: Any
label: Any
leaflet: Any
left_drawer: Any
line_plot: Any
linear_progress: Any
link: Any
link_target: Any
list: Any
log: Any
markdown: Any
matplotlib: Any
menu: Any
menu_item: Any
mermaid: Any
navigate: Any
notification: Any
notify: Any
number: Any
on: Any
on_exception: Any
page: Any
page_scroller: Any
page_sticky: Any
page_title: Any
pagination: Any
plotly: Any
pyplot: Any
query: Any
radio: Any
range: Any
rating: Any
refreshable: Any
refreshable_method: Any
restructured_text: Any
right_drawer: Any
row: Any
run: Any
run_javascript: Any
run_with: Any
scene: Any
scene_view: Any
scroll_area: Any
select: Any
separator: Any
skeleton: Any
slide_item: Any
slider: Any
space: Any
spinner: Any
splitter: Any
state: Any
step: Any
stepper: Any
stepper_navigation: Any
sub_pages: Any
switch: Any
tab: Any
tab_panel: Any
tab_panels: Any
table: Any
tabs: Any
teleport: Any
textarea: Any
time: Any
time_input: Any
timeline: Any
timeline_entry: Any
timer: Any
toggle: Any
tooltip: Any
tree: Any
update: Any
upload: Any
video: Any
xterm: Any

def builder(layout: Any) -> Any: ...
def form(source: Any, flavor: str = "") -> Any: ...
def table(source: Any, variant: str = "std") -> Any: ...

__all__: list[str]
